import { Router } from "express";
import { getGeminiGeneratedJobs } from "../controllers/geminiJobs.controller.js";

const router = Router();

// Get jobs generated by Gemini AI
router.get("/", getGeminiGeneratedJobs);

export default router;
